name: Build & Test

on:
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # check out repository under $GITHUB_WORKSPACE, so job can access it
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}      
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build Solution
      run: |  
        cd <project>
        dotnet pack -c Release -o out  

     - name: Push generated package to GitHub registry
      run: dotnet nuget push ./<project>/out/*.nupkg --skip-duplicate --no-symbols true